# Generated by Django 5.2.3 on 2025-07-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_rename_post_blog_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='author',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
